# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(469, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_joinVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_joinVideo.setGeometry(QtCore.QRect(370, 230, 75, 31))
        self.btn_joinVideo.setObjectName("btn_joinVideo")
        self.btn_splitVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_splitVideo.setGeometry(QtCore.QRect(370, 20, 75, 41))
        self.btn_splitVideo.setObjectName("btn_splitVideo")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 331, 201))
        self.listWidget.setObjectName("listWidget")
        self.btn_downVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_downVideo.setGeometry(QtCore.QRect(370, 90, 75, 41))
        self.btn_downVideo.setObjectName("btn_downVideo")
        self.btn_downAll = QtWidgets.QPushButton(self.centralwidget)
        self.btn_downAll.setGeometry(QtCore.QRect(370, 160, 75, 41))
        self.btn_downAll.setObjectName("btn_downAll")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 280, 451, 31))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.textE_width = QtWidgets.QTextEdit(self.centralwidget)
        self.textE_width.setGeometry(QtCore.QRect(40, 230, 121, 31))
        self.textE_width.setObjectName("textE_width")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 240, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 240, 31, 16))
        self.label_3.setObjectName("label_3")
        self.textE_height = QtWidgets.QTextEdit(self.centralwidget)
        self.textE_height.setGeometry(QtCore.QRect(220, 230, 121, 31))
        self.textE_height.setObjectName("textE_height")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_joinVideo.setText(_translate("MainWindow", "拼接视频"))
        self.btn_splitVideo.setText(_translate("MainWindow", "分析JSON"))
        self.btn_downVideo.setText(_translate("MainWindow", "下载视频"))
        self.btn_downAll.setText(_translate("MainWindow", "全部下载"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "宽："))
        self.label_3.setText(_translate("MainWindow", "高："))
